### ISSUE TITLE
Another Question about spatial_map_train.npy

### ISSUE THREAD

**Issue by H-Li24** [toshi-k/kaggle-trends-assessment-prediction#2]
Hi Toshi san,

When reading your code, it seems that it needs to use two documents "spatial_map_train.npy" and "spatial_map_test.npy".
I don't know how to generate these documents, could you give me some guidance?

I really want to run your code successfully...

Thank you very much!

Henry

**Comment by toshi-k** [comment]
`spatial_map_train.npy` and `spatial_map_test.npy' are generated by preprocessing. I shared the code for them too.
https://github.com/toshi-k/kaggle-trends-assessment-prediction/blob/master/source/01_preprocess/spatial_map.py
